MT#55401 pua and pua_dialoginfo improvements
We are seeing a lot of error messages like:

> ERROR: pua [pua_db.c:895]: get_record_puadb(): Too many rows found (2)

After some investigation I come up with a couple of fixes:

* pua: improve the query to support caller|callee with same pres_id (same dialog)
* pua_dialoginfo: support uuid to generate pres_id to improve randomness

Change-Id: I43d5c58fe20c776b03af217f644443d800c9453e
(cherry picked from commit 95a5a1678ba042641e255993883d7a9621c6d360)