TT#87201 ndb_redis remove useless error message
> ERROR: ndb_redis [redis_client.c:903]: redisc_exec_argv(): Redis error: Server closed the connection

Change-Id: Ife5be1087993f54e785a11e60e1b0f0e8d407547
(cherry picked from commit 590f81e3a021d17d237109aa3ba99bec15807743)