Build-Depend on libxmlrpc-c3-dev older than 1.16.07
Fixes build error caused by libxmlrpc-c3-dev's squeeze backport
version 1.16.07-1:

| abyss_data.c:219: error: expected ')' before '*' token
| abyss_data.c:236: error: expected ')' before '*' token
| abyss_data.c:249: error: expected ')' before '*' token
| abyss_data.c:287: error: expected ')' before '*' token